users-endpoints-flag:
  variations:
    access: true
    block: false
  targeting:
    - name: Allow web channel access
      query: key eq "web"
      variation: access
    - name: Allow mobile channel access
      query: key eq "mobile"
      variation: access
    name: Wrong semantics
  defaultRule:
    variation: block

