users-endpoints-flag:
  variations:
    access: true
    block: false
  targeting:
    - name: Allow web channel access
      query: key eq "web"
      variation: access
    - name: Allow mobile channel access
      query: key eq "mobile"
      variation: block
  defaultRule:
    variation: block
logging-flag:
  variations:
    variation-true: true
    variation-false: false
  targeting:
    - name: Set debug logging
      query: key eq "debug"
      variation: variation-false
    - name: Set client request logging
      query: key eq "http-client-requests"
      variation: variation-true
  defaultRule:
    variation: error
